### ISSUE TITLE
Make an official Redis adapter for Node-Casbin

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/redis-adapter#1]
We have a 3rd-party one but it's no longer maintained: https://github.com/NandaKishorJeripothula/node-casbin-redis-adapter

**Comment by 0xethsign** [comment]
Is anyone working on this? I'd like to spend some time on this.

**Comment by hsluoyz** [comment]
@smrpn sounds good! Welcome to contribute to this repo via PR, thanks!

**Comment by hsluoyz** [comment]
@smrpn plz fix package-lock.json, we use Yarn. Also plz add tests and badges like CI, code coverage.
