### ISSUE TITLE
Creating enforce  with newEnforcer and NodeRedisAdapter not works

### ISSUE THREAD

**Issue by MemoBeGo** [node-casbin/redis-adapter#13]
Hi, 

I'm sure redis is connected but when i try to create the enforcer next lines after newEnforcer(...) never are reached

```
        this.redisAdapter = await NodeRedisAdapter.newAdapter(
          {
            host: '127.0.0.1',
            port: 6379,
          },
          { database: 0 },
        );


        this.redisEnforcer = await newEnforcer(model, this.redisAdapter);

        // never executes next lines and no throw any error

```

Any idea? Thanks

**Comment by hsluoyz** [comment]
@MemoBeGo prove the bug in source code level, debug it

**Comment by MemoRodMx** [comment]
@khayong Thanks,

i resolved the issue modifying my model.conf which was incomplete (thanks to sqllite adapter errors).

Other issue is: i can't import  NodeRedisAdapter from ''casbin-redis-adapter", i've needed to copy adapter file to my project to make it working

I working on a nestjs (typescript) project fyi

✌️
