### ISSUE TITLE
Add package.json, remove package-lock.json, use yarn.lock. Also plz add tests and badges like CI, code coverage.

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/redis-adapter#3]

**Comment by hsluoyz** [comment]
@smrpn

**Comment by 0xethsign** [comment]
> @smrpn 

I'm writing blogs for casbin-rust, also have to fix the benchmark action there. Will definitely do this after these. Noted on my to-do.

**Comment by Zxilly** [comment]
working on this
